# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQWu_1TS39Ir0Ff2PBPZjdO1T41Va1z3
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv("homeprices.csv")

df

plt.xlabel("area")
plt.ylabel("price")
plt.scatter(df.area, df.price, color="blue",marker=".")

new_df = df.drop("price" , axis="columns")
new_df

price = df.price
price

reg = linear_model.LinearRegression()
reg.fit(new_df, price)

reg.predict([[3300]])

reg.intercept_

reg.coef_[0]

3300 * 180616.43835616432 + 135.78767123287673

my_file = pd.read_csv("canada_per_capita_income.csv")
my_file.head()

plt.xlabel("year")
plt.ylabel("per capita income")
plt.scatter(my_file.year, my_file["per capita income (US$)"], color="blue", marker=".")

new_file = my_file.drop("year" , axis="columns")
new_file.head()

year = my_file.year
year.head()

reg = linear_model.LinearRegression()
reg.fit( new_file, year)

reg.predict([[2020]])

reg.intercept_

reg.coef_

2020 * 1972.6536140098344 + 0.00107538

